# Generated by Django 4.1.2 on 2022-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nickname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('profile_image_url', models.URLField()),
                ('github_api_url', models.URLField()),
            ],
            options={
                'ordering': ['nickname', 'created_at'],
            },
        ),
    ]
