# Generated by Django 4.1.2 on 2022-10-16 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 15, 48, 18, 391957, tzinfo=datetime.timezone.utc)),
        ),
    ]
