# Generated by Django 4.1.2 on 2022-10-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
