# Generated by Django 4.1.2 on 2022-10-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_last_login'),
        ('lecture', '0002_alter_lecture_options_lecture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lectures', to='authentication.user'),
        ),
    ]
