# Generated by Django 4.1.2 on 2022-11-03 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='answer_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='skeleton_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
