# Generated by Django 4.1.2 on 2022-10-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        ('authentication', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='lecture.lecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='authentication.user')),
            ],
            options={
                'ordering': ['lecture_id', 'created_at'],
            },
        ),
    ]
