# Generated by Django 4.1.2 on 2022-11-04 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='lecture.lecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lecture_id', 'created_at'],
            },
        ),
    ]
