name: Django CI

on:
  push:
    branches: [ "main", "feature/*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        python backend/manage.py makemigrations --settings=backend.settings.test backend
        python backend/manage.py migrate --settings=backend.settings.test backend
    - name: Run Tests
      run: |
        python backend/manage.py test --settings=backend.settings.test backend
